f = 'AGGTAACTTGTATAATGATCGGGACACAAGCAGGGTCTCGGAAAGGCGAGAGACGTATCCTTCCTGGGGCGATGTATCATAGTCGGGTCACAATCGAATCGACATTCCCCCTCTGCATACCTGACTCTCACGCGCGTCATGACGGTCTTCCAAACCTTCACTTGTTGTAGCGTCTACCCTTTCCAACGGTAACGAATCAGTCTTTCTCACTCAGCATAAGTAAAGACCGTCACCTGGACAACACTCCGTTCGCGCTGTGTTCGAACAGTCTCCTGCGCAATCCGTTGTCTGTCCATTGGCATTAGGACCATTAGGTGGGGGGGGGAACCGACATTCGGGTCGCCCCGTTTCGGACACCGAGGTGCGAACCGAAACGCGGGTAGTGTAAGTTGAACAGGGTGGTTCTGGCCTAATTTCCGTTGTCAATGCCTGAGTTTACCAAGGTAGTACAAGGGAATCAGACCCTGTTGTACCAGCTAGTACTTCCTCTAGCACTGCTCGCCCTGTTGCTGATGTATTGAGACTGGACACCTCTAGGAGACGGAGGGATGGCATACACCAAGTCCTCGCGACTCTCCTGCGGCCTGTGAGGACCTCCATCACTAAGCGTCGCGGGCATTCATCCCTCACCTAGTACGTTGGCCCGTGATGGGAAGAGGATTCGCCAAAACAAGGGAGAGTAGCTGGAGGATGGAACCGCGCGTCCTTGACCCTAGTCCCATATTAAGGAACGCCTTAGTATAGCGACGCAGGATGTGTGGTGTGGCTTCCAGGTGGGCCAGGCAACTCGTTGCCCAATCAGTAGACGCATAGCAAACCGCCCTTTTAGACCCGAGACACTCTCTTCAATACAA'
A=0
C=0
G=0
T=0

for i in f:
    if i=="A":
        A+=1
    if i=="C":
        C+=1
    if i=="G":
        G+=1
    if i=="T":
        T+=1
print str(A) +' ' +str(C) +' ' +str(G)+' ' + str(T)
